"""oskill element manifest — machine-readable registry of all public elements."""  # pragma: no cover  # noqa: E501

from __future__ import annotations

VERSION = "2.0.0"

ELEMENTS: list[str] = [
    # Group 1: Performance
    "bootstrap_sharpe",
    "psr_dsr",
    "factor_attribution",
    "regime_aware_performance",
    # Group 2: Validation
    "walk_forward_optimization",
    "cpcv_pipeline",
    "regime_aware_rolling",
    # Group 3: Distribution
    "distribution_shift_test",
    "detect_outliers_robust",
    "bootstrap_distribution",
    # Group 4: Similarity
    "historical_analogy_search",
    "regime_transition_analysis",
    "commodity_ratio_analytics",
    "geopolitical_risk_index",
    # Group 5: Prediction
    "calibration_analysis",
    # Group 6: Signal Detection
    "adx",
    "cusum_detector",
    "platt_calibration",
    # Group 7: Point Process
    "fit_hawkes",
    # Group 8: Causal
    "symbolic_transfer_entropy",
    # Group 9: HMM
    "gaussian_hmm",
    # Phase 1 additions (v1.4.0):
    "signal_ensemble",
    "weighted_signal_aggregation",
    "deterministic_llm_call",
    "prompt_fingerprint",
    # Phase 2 additions (v1.5.0):
    "ledoit_wolf_shrinkage",
    "denoised_covariance",
    "probability_of_backtest_overfitting",
    "deflated_sharpe_ratio",
    "factor_quantile_returns",
    # Phase 3 additions (v1.6.0):
    "tool_call_validator",
    "chain_of_thought_extractor",
    "llm_response_consistency",
    "multi_model_ensemble",
    "faithfulness_score",
    "chunking_strategy_apply",
    "reranker_score",
    # Phase 4 prerequisites (v1.7.0):
    "triple_barrier_label",
    "factor_ic",
    "bocpd_bayesian",
    "pelt_change_point",
    # Phase 5B: ml_finance (v1.8.0):
    "meta_labeling",
    "sample_uniqueness_weights",
    "return_attribution_weights",
    "fractional_differentiation",
    "cusum_filter",
    "bet_sizing",
    # Phase 5C: factor models (v1.8.0):
    "fama_french_5_factor_model",
    "carhart_4_factor_model",
    "barra_style_decomposition",
    "factor_neutralization",
    # Phase 4: Microstructure (v1.8.0):
    "order_flow_imbalance",
    "dollar_bar_aggregation",
    "volume_imbalance_bar",
    "tick_imbalance_bar",
    "kyle_lambda_estimator",
    "amihud_illiquidity",
    "hawkes_branching_ratio",
    # Phase 4: State Space (v1.8.0):
    "kalman_filter_pipeline",
    "kalman_smoother",
    "particle_filter_pipeline",
    # Phase 7B: Conformal Prediction (v1.10.0):
    "conformal_prediction_interval",
    "adaptive_conformal_inference",
    "conformal_with_change_points",
    # Phase 7C: Distributional RL (v1.10.0):
    "quantile_regression_loss",
    "implicit_quantile_loss",
    # Phase 7D: Causal Discovery (v1.10.0):
    "pcmci_causal_discovery",
    "structural_causal_model_fit",
    # Phase 7E: Generative (v1.10.0):
    "ddpm_synthetic_path_generator",
    # Phase 9A: Signature (v1.11.0):
    "signature_kernel",
    "signature_based_pricing",
    # Phase 9A: Market Making (v1.11.0):
    "avellaneda_stoikov_quotes",
    "cartea_jaimungal_optimal_quotes",
    # Phase 9A: Operational Risk (v1.11.0):
    "operational_risk_lda",
    # Phase 10: Behavioral Finance (v2.0.0)
    "cpt_portfolio_optimize",
    "maxmin_expected_utility_portfolio",
    "cpt_portfolio_analytical",
    "salience_asset_pricing",
    # Phase 10: Networks + Systemic Risk (v2.0.0)
    "financial_network_centrality",
    "eisenberg_noe_clearing",
    "systemic_risk_metrics",
    "contagion_simulate",
    # Phase 10: Spectral + Portfolio (v2.0.0)
    "graph_laplacian_compute",
    "spectral_asset_clustering",
    "hierarchical_risk_parity_v2",
    "ssd_milp_optimizer",
    # Phase 10: Microstructure (v2.0.0)
    "order_book_state_hawkes",
    # Phase 10: Robust Control (v2.0.0)
    "multiplier_preferences_robust",
    "variational_preferences_estimate",
    "smooth_ambiguity_portfolio",
    # Phase 10: Recursive Utility (v2.0.0)
    "epstein_zin_solver",
    # Sprint 0 additions (v2.5.0)
    "aggregate_signal_returns",
    "portfolio_metrics_summary",
    "trade_pnl_statistics",
    "multi_dim_nearest_search",
    "forward_outcome_distribution",
    "rule_based_classifier",
    "rule_based_veto_check",
    "dsl_rule_validate",
    "dsl_rule_evaluate",
    "multi_state_classify",
    "disclosure_event_scoring",
    "event_theme_cluster",
    "sector_capital_rotation_detect",
    "market_rules_backtest_run",
    # --- Helios Wave 01: Crypto Fusion Scorers (7) ---
    "trend_score",
    "flow_score",
    "sentiment_score",
    "onchain_score",
    "derivatives_score",
    "macro_score",
    "support_resistance_score",
    # --- Helios Wave 01: Crypto Environ Processors (10) ---
    "derivatives_agg_compute",
    "dex_truth_compute",
    "dex_truth_dydx_compute",
    "dex_truth_gmx_compute",
    "etf_flow_compute",
    "etf_flow_per_ticker_compute",
    "macro_environ_compute",
    "onchain_aggregate_compute",
    "exchange_netflow_compute",
    "options_environ_compute",
    # --- Helios Wave 01: Crypto Data/Alert/Collect (18) ---
    "get_symbol_basis",
    "get_symbol_daily_klines",
    "get_symbol_onchain_metrics",
    "get_symbol_options_skew",
    "get_symbol_max_pain",
    "get_etf_inflow_7d",
    "get_30d_returns_stddev",
    "fear_greed_fetch_all",
    "dex_cex_check",
    "proxy_check_and_notify",
    "evaluate_stale",
    "stale_check_and_notify",
    "compute_signal_quality",
    "collect_cycle",
    "collect_sectors",
    "collect_sentiment",
    "store_market",
    "collect_write_event",
    # --- B10 --- Tide v4 step2 oskills (12)
    "macro_surprise_compute",
    "macro_cycle_engine_v2",
    "policy_sector_attribution",
    "seat_winrate_aggregator",
    "unknown_seats_audit_loop",
    "sector_strength_aggregator",
    "candidate_universe_builder_v3",
    "similar_context_injector",
    "industry_valuation_percentile",
    "discipline_vs_violation_winrate_compute",
    "system_history_aggregator",
    "equity_curve_3seg_compute",
    # General Purpose (MathModelAgent SKILL 3O 内化, v4.15.0)
    "typst_minimal_doc",
    "typst_format_check",
    "typst_probe",
    "typst_compile",
    "detect_platform",
    "check_dependencies",
    "install_commands",
    "run_doctor",
    "resolve_template",
    "list_figure_templates",
    "render_figure_template",
    # General Purpose (MathModelAgent SKILL 3O 内化, v4.16.0)
    "drawio_node",
    "drawio_edge",
    "drawio_doc",
    "export_drawio",
    "validate_drawio",
    "render_drawio",
    "resolve_config",
    "run_text_gate",
    "compile_paper",
    "pdf_pages",
    "run_verity",
    # Engineering Workflow (mattpocock skills 3O 内化, v4.17.0)
    "interview_frontier",
    "interview_pending_facts",
    "interview_progress",
    "is_interview_complete",
    "record_interview_answers",
    "record_interview_facts",
    "resolve_interview_answer",
    "scan_standards",
    "scan_spec_coverage",
    "review_diff",
    "read_glossary",
    "upsert_term",
    "should_write_adr",
    "write_adr",
    "tickets_next_runnable",
    "ticket_set_status",
    "tickets_check_cycles",
    "pipeline_next_action",
    "pipeline_transition",
    "workflow_to_dict",
    "workflow_from_dict",
    # Rulebooks (agent-rules-books 3O 内化, v4.18.0)
    "list_rulebooks",
    "get_rulebook",
    "rules_sections",
    "select_rulebooks",
    # Agent Book (ai-agent-book 3O 内化, v4.19.0)
    "run_suite",
    "compare_runs",
    "paired_t_test",
    "wilcoxon_signed_rank",
    "cohens_d",
    "ExperienceStore",
    "format_experiences",
    "ContextPool",
    "run_voice_pipeline",
    "interrupt_turn",
    # md2wechat (3O 内化, v4.20.0)
    "ResourceCatalog",
    "AntiNoiseValidator",
    "md_to_wechat_html",
    "produce_article",
    "publish_draft",
    "ArticleStore",
    # Graft (NanoNets, 3O 内化, v4.21.0)
    "semantic_build",
    "incremental_refresh",
    "stale_nodes",
    "render_node_markdown",
    "parse_wikilinks",
    "write_agent_instructions",
    "plan_wiring",
    "list_agents",
    # Graphify / Strix (3O 内化, v4.22.0)
    "KnowledgeGraph",
    "semantic_to_graph",
    "run_pentest_loop",
    "verify_finding",
    # TencentDB Agent Memory (3O 内化, v4.23.0)
    "rrf_merge",
    "hybrid_search",
    "bm25_score",
    "DistillPipeline",
    "AssetRegistry",
    # Cypress (3O 内化, v4.24.0)
    "retry_until",
    "wait_actionable",
    "expect_eventually",
    # FDE book (3O 内化, v4.25.0)
    "compute_health",
    "watchdog",
    "normalize",
    # AiToEarn (3O 内化, v4.26.0)
    "publish_to",
    "batch_draft",
    "content_limits",
    "register_platform",
    "list_platforms",
    "settle",
    # Pixel2Motion (3O 内化, v4.27.0)
    "iou_score",
    "svg_path_audit",
    "smoothness_gate",
    "complexity_ladder",
    # FDE book 2/7章 (3O 内化, v4.28.0)
    "mvd_check",
    "MvdPipeline",
    "PlaybookLibrary",
    "evaluate_productization",
    # Auto-Deep-Research (3O 内化, v4.29.0)
    "tools_to_prompt",
    "wrap_tools",
    "parse_function_tags",
    "convert_to_tool_calls",
    "adapt_call",
    # Dify (3O 内化, v4.30.0)
    "WorkflowDAG",
    "topological_execute",
    "validate_dsl",
    "render_template",
    "PluginRegistry",
    # Dify Agent (3O 内化, v4.31.0)
    "run_agent",
    "run_function_calling",
    "run_react",
    "run_plan",
    # Deep-dive batch (2-8, v4.32.0)
    "FlowRunner",
    "FlowBroker",
    "BanditRouter",
    "OffloadPipeline",
    "SquadOrchestrator",
    "parse_python_tree",
    "Marketplace",
    "fit_smooth_cubic",
    # Remaining value batch (v4.33.0)
    "build_rag_pipeline",
    "moderate",
    "ConversationVars",
    "CodeGraphBuilder",
    "TriageFlow",
    "HealthMonitor",
]

CATEGORIES: dict[str, list[str]] = {
    "performance": [
        "bootstrap_sharpe",
        "psr_dsr",
        "factor_attribution",
        "regime_aware_performance",
    ],
    "validation": ["walk_forward_optimization", "cpcv_pipeline", "regime_aware_rolling"],
    "distribution": [
        "distribution_shift_test",
        "detect_outliers_robust",
        "bootstrap_distribution",
    ],
    "similarity": [
        "historical_analogy_search",
        "regime_transition_analysis",
        "commodity_ratio_analytics",
        "geopolitical_risk_index",
    ],
    "prediction": ["calibration_analysis"],
    "signal_detection": ["adx", "cusum_detector", "platt_calibration"],
    "point_process": ["fit_hawkes"],
    "causal": [
        "symbolic_transfer_entropy",
        "pcmci_causal_discovery",
        "structural_causal_model_fit",
    ],
    "hmm": ["gaussian_hmm"],
    "signals": ["signal_ensemble", "weighted_signal_aggregation"],
    "llm": [
        "deterministic_llm_call",
        "prompt_fingerprint",
        "tool_call_validator",
        "chain_of_thought_extractor",
        "llm_response_consistency",
        "multi_model_ensemble",
        "faithfulness_score",
    ],
    "rag": ["chunking_strategy_apply", "reranker_score"],
    "covariance": ["ledoit_wolf_shrinkage", "denoised_covariance"],
    "validation_phase2": [
        "probability_of_backtest_overfitting",
        "deflated_sharpe_ratio",
    ],
    "ml_labeling": ["triple_barrier_label"],
    "ml_finance": [
        "meta_labeling",
        "sample_uniqueness_weights",
        "return_attribution_weights",
        "fractional_differentiation",
        "cusum_filter",
        "bet_sizing",
    ],
    "change_point": ["bocpd_bayesian", "pelt_change_point"],
    "factor": [
        "factor_ic",
        "factor_quantile_returns",
        "fama_french_5_factor_model",
        "carhart_4_factor_model",
        "barra_style_decomposition",
        "factor_neutralization",
    ],
    "microstructure": [
        "order_flow_imbalance",
        "dollar_bar_aggregation",
        "volume_imbalance_bar",
        "tick_imbalance_bar",
        "kyle_lambda_estimator",
        "amihud_illiquidity",
        "hawkes_branching_ratio",
    ],
    "state_space": [
        "kalman_filter_pipeline",
        "kalman_smoother",
        "particle_filter_pipeline",
    ],
    "conformal": [
        "conformal_prediction_interval",
        "adaptive_conformal_inference",
        "conformal_with_change_points",
    ],
    "distributional_rl": [
        "quantile_regression_loss",
        "implicit_quantile_loss",
    ],
    "generative": [
        "ddpm_synthetic_path_generator",
    ],
    # Phase 9A categories
    "signature": ["signature_kernel", "signature_based_pricing"],
    "market_making": ["avellaneda_stoikov_quotes", "cartea_jaimungal_optimal_quotes"],
    "operational_risk": ["operational_risk_lda"],
    # Phase 10 categories
    "behavioral_portfolio": [
        "cpt_portfolio_optimize",
        "maxmin_expected_utility_portfolio",
        "cpt_portfolio_analytical",
        "salience_asset_pricing",
    ],
    "networks": [
        "financial_network_centrality",
        "eisenberg_noe_clearing",
        "systemic_risk_metrics",
        "contagion_simulate",
    ],
    "spectral_portfolio": [
        "graph_laplacian_compute",
        "spectral_asset_clustering",
        "hierarchical_risk_parity_v2",
        "ssd_milp_optimizer",
    ],
    "robust_control": [
        "multiplier_preferences_robust",
        "variational_preferences_estimate",
        "smooth_ambiguity_portfolio",
    ],
    "recursive_utility": ["epstein_zin_solver"],
    "state_hawkes": ["order_book_state_hawkes"],
    # B10 — Tide v4 step2 (12)
    "tide_step2": [
        "macro_surprise_compute",
        "macro_cycle_engine_v2",
        "policy_sector_attribution",
        "seat_winrate_aggregator",
        "unknown_seats_audit_loop",
        "sector_strength_aggregator",
        "candidate_universe_builder_v3",
        "similar_context_injector",
        "industry_valuation_percentile",
        "discipline_vs_violation_winrate_compute",
        "system_history_aggregator",
        "equity_curve_3seg_compute",
    ],
    "cognitive": [
        "cognitive_update",
    ],
    # General Purpose (MathModelAgent SKILL 3O 内化, v4.15.0)
    "general_purpose": [
        "typst_minimal_doc",
        "typst_format_check",
        "typst_probe",
        "typst_compile",
        "detect_platform",
        "check_dependencies",
        "install_commands",
        "run_doctor",
        "resolve_template",
        "list_figure_templates",
        "render_figure_template",
        "drawio_node",
        "drawio_edge",
        "drawio_doc",
        "export_drawio",
        "validate_drawio",
        "render_drawio",
        "resolve_config",
        "run_text_gate",
        "compile_paper",
        "pdf_pages",
        "run_verity",
        # Engineering Workflow (mattpocock skills 3O 内化, v4.17.0)
        "interview_frontier",
        "interview_pending_facts",
        "interview_progress",
        "is_interview_complete",
        "record_interview_answers",
        "record_interview_facts",
        "resolve_interview_answer",
        "scan_standards",
        "scan_spec_coverage",
        "review_diff",
        "read_glossary",
        "upsert_term",
        "should_write_adr",
        "write_adr",
        "tickets_next_runnable",
        "ticket_set_status",
        "tickets_check_cycles",
        "pipeline_next_action",
        "pipeline_transition",
        "workflow_to_dict",
        "workflow_from_dict",
        "list_rulebooks",
        "get_rulebook",
        "rules_sections",
        "select_rulebooks",
        "standards_rules",
        # Agent Book (ai-agent-book 3O 内化, v4.19.0)
        "run_suite",
        "compare_runs",
        "paired_t_test",
        "wilcoxon_signed_rank",
        "cohens_d",
        "ExperienceStore",
        "format_experiences",
        "ContextPool",
        "run_voice_pipeline",
        "interrupt_turn",
        "ResourceCatalog",
        "AntiNoiseValidator",
        "md_to_wechat_html",
        "produce_article",
        "publish_draft",
        "ArticleStore",
        "semantic_build",
        "incremental_refresh",
        "stale_nodes",
        "render_node_markdown",
        "parse_wikilinks",
        "write_agent_instructions",
        "plan_wiring",
        "list_agents",
        "KnowledgeGraph",
        "semantic_to_graph",
        "run_pentest_loop",
        "verify_finding",
        "rrf_merge",
        "hybrid_search",
        "bm25_score",
        "DistillPipeline",
        "AssetRegistry",
        "retry_until",
        "wait_actionable",
        "expect_eventually",
        "compute_health",
        "watchdog",
        "normalize",
        "publish_to",
        "batch_draft",
        "content_limits",
        "register_platform",
        "list_platforms",
        "settle",
        "iou_score",
        "svg_path_audit",
        "smoothness_gate",
        "complexity_ladder",
        "mvd_check",
        "MvdPipeline",
        "PlaybookLibrary",
        "evaluate_productization",
        "tools_to_prompt",
        "wrap_tools",
        "parse_function_tags",
        "convert_to_tool_calls",
        "adapt_call",
        "WorkflowDAG",
        "topological_execute",
        "validate_dsl",
        "render_template",
        "PluginRegistry",
        "run_agent",
        "run_function_calling",
        "run_react",
        "run_plan",
        "FlowRunner",
        "FlowBroker",
        "BanditRouter",
        "OffloadPipeline",
        "SquadOrchestrator",
        "parse_python_tree",
        "Marketplace",
        "fit_smooth_cubic",
        "build_rag_pipeline",
        "moderate",
        "ConversationVars",
        "CodeGraphBuilder",
        "TriageFlow",
        "HealthMonitor",
    ],
}

STABILITY: dict[str, str] = {
    "bootstrap_sharpe": "stable",
    "psr_dsr": "stable",
    "factor_attribution": "stable",
    "regime_aware_performance": "stable",
    "walk_forward_optimization": "stable",
    "cpcv_pipeline": "stable",
    "regime_aware_rolling": "stable",
    "distribution_shift_test": "stable",
    "detect_outliers_robust": "stable",
    "bootstrap_distribution": "stable",
    "historical_analogy_search": "stable",
    "regime_transition_analysis": "stable",
    "commodity_ratio_analytics": "stable",
    "geopolitical_risk_index": "stable",
    "calibration_analysis": "stable",
    "adx": "stable",
    "cusum_detector": "stable",
    "platt_calibration": "stable",
    "fit_hawkes": "stable",
    "symbolic_transfer_entropy": "stable",
    "gaussian_hmm": "stable",
    # Phase 1 additions:
    "signal_ensemble": "stable",
    "weighted_signal_aggregation": "stable",
    "deterministic_llm_call": "experimental",
    "prompt_fingerprint": "stable",
    # Phase 2 additions:
    "ledoit_wolf_shrinkage": "stable",
    "denoised_covariance": "stable",
    "probability_of_backtest_overfitting": "stable",
    "deflated_sharpe_ratio": "stable",
    "factor_quantile_returns": "stable",
    # Phase 3 additions:
    "tool_call_validator": "experimental",
    "chain_of_thought_extractor": "experimental",
    "llm_response_consistency": "experimental",
    "multi_model_ensemble": "experimental",
    "faithfulness_score": "experimental",
    "chunking_strategy_apply": "experimental",
    "reranker_score": "experimental",
    # Phase 4 + 5 additions:
    "triple_barrier_label": "stable",
    "factor_ic": "stable",
    "bocpd_bayesian": "stable",
    "pelt_change_point": "stable",
    "meta_labeling": "stable",
    "sample_uniqueness_weights": "stable",
    "return_attribution_weights": "stable",
    "fractional_differentiation": "stable",
    "cusum_filter": "stable",
    "bet_sizing": "stable",
    "fama_french_5_factor_model": "stable",
    "carhart_4_factor_model": "stable",
    "barra_style_decomposition": "stable",
    "factor_neutralization": "stable",
    # Phase 4: Microstructure
    "order_flow_imbalance": "stable",
    "dollar_bar_aggregation": "stable",
    "volume_imbalance_bar": "stable",
    "tick_imbalance_bar": "stable",
    "kyle_lambda_estimator": "stable",
    "amihud_illiquidity": "stable",
    "hawkes_branching_ratio": "stable",
    # Phase 4: State Space
    "kalman_filter_pipeline": "stable",
    "kalman_smoother": "stable",
    "particle_filter_pipeline": "stable",
    # Phase 7B: Conformal Prediction
    "conformal_prediction_interval": "stable",
    "adaptive_conformal_inference": "stable",
    "conformal_with_change_points": "experimental",
    # Phase 7C: Distributional RL
    "quantile_regression_loss": "stable",
    "implicit_quantile_loss": "stable",
    # Phase 7D: Causal Discovery
    "pcmci_causal_discovery": "stable",
    "structural_causal_model_fit": "stable",
    # Phase 7E: Generative
    "ddpm_synthetic_path_generator": "experimental",
    # Phase 9A additions
    "signature_kernel": "stable",
    "signature_based_pricing": "stable",
    "avellaneda_stoikov_quotes": "stable",
    "cartea_jaimungal_optimal_quotes": "stable",
    "operational_risk_lda": "stable",
    # Phase 10 additions
    "cpt_portfolio_optimize": "stable",
    "maxmin_expected_utility_portfolio": "stable",
    "financial_network_centrality": "stable",
    "eisenberg_noe_clearing": "stable",
    "systemic_risk_metrics": "stable",
    "contagion_simulate": "stable",
    "graph_laplacian_compute": "stable",
    "spectral_asset_clustering": "stable",
    "hierarchical_risk_parity_v2": "stable",
    "order_book_state_hawkes": "stable",
    "multiplier_preferences_robust": "stable",
    "variational_preferences_estimate": "stable",
    "cpt_portfolio_analytical": "stable",
    "salience_asset_pricing": "stable",
    "smooth_ambiguity_portfolio": "stable",
    "ssd_milp_optimizer": "stable",
    "epstein_zin_solver": "stable",
    # Sprint 0 additions (v2.5.0)
    "aggregate_signal_returns": "experimental",
    "portfolio_metrics_summary": "experimental",
    "trade_pnl_statistics": "experimental",
    "multi_dim_nearest_search": "experimental",
    "forward_outcome_distribution": "experimental",
    "rule_based_classifier": "experimental",
    "rule_based_veto_check": "experimental",
    "dsl_rule_validate": "experimental",
    "dsl_rule_evaluate": "experimental",
    "multi_state_classify": "experimental",
    "disclosure_event_scoring": "experimental",
    "event_theme_cluster": "experimental",
    "sector_capital_rotation_detect": "experimental",
    "market_rules_backtest_run": "experimental",
    # Stratum B2 (v3.9.0)
    "cross_layer_search": "experimental",
    "recommend_content": "experimental",
    "resolve_conflict": "experimental",
    "merge_platform_user_results": "experimental",
    "lint_substrate_graph": "experimental",
    "check_reference_integrity": "experimental",
    "cognitive_update": "experimental",
    # General Purpose (MathModelAgent SKILL 3O 内化, v4.15.0)
    "typst_minimal_doc": "experimental",
    "typst_format_check": "experimental",
    "typst_probe": "experimental",
    "typst_compile": "experimental",
    "detect_platform": "experimental",
    "check_dependencies": "experimental",
    "install_commands": "experimental",
    "run_doctor": "experimental",
    "resolve_template": "experimental",
    "list_figure_templates": "experimental",
    "render_figure_template": "experimental",
    # General Purpose (MathModelAgent SKILL 3O 内化, v4.16.0)
    "drawio_node": "experimental",
    "drawio_edge": "experimental",
    "drawio_doc": "experimental",
    "export_drawio": "experimental",
    "validate_drawio": "experimental",
    "render_drawio": "experimental",
    "resolve_config": "experimental",
    "run_text_gate": "experimental",
    "compile_paper": "experimental",
    "pdf_pages": "experimental",
    "run_verity": "experimental",
    # Engineering Workflow (mattpocock skills 3O 内化, v4.17.0)
    "interview_frontier": "experimental",
    "interview_pending_facts": "experimental",
    "interview_progress": "experimental",
    "is_interview_complete": "experimental",
    "record_interview_answers": "experimental",
    "record_interview_facts": "experimental",
    "resolve_interview_answer": "experimental",
    "scan_standards": "experimental",
    "scan_spec_coverage": "experimental",
    "review_diff": "experimental",
    "read_glossary": "experimental",
    "upsert_term": "experimental",
    "should_write_adr": "experimental",
    "write_adr": "experimental",
    "tickets_next_runnable": "experimental",
    "ticket_set_status": "experimental",
    "tickets_check_cycles": "experimental",
    "pipeline_next_action": "experimental",
    "pipeline_transition": "experimental",
    "workflow_to_dict": "experimental",
    "workflow_from_dict": "experimental",
    "list_rulebooks": "experimental",
    "get_rulebook": "experimental",
    "rules_sections": "experimental",
    "select_rulebooks": "experimental",
    "standards_rules": "experimental",
    # Agent Book (ai-agent-book 3O 内化, v4.19.0)
    "run_suite": "experimental",
    "compare_runs": "experimental",
    "paired_t_test": "experimental",
    "wilcoxon_signed_rank": "experimental",
    "cohens_d": "experimental",
    "ExperienceStore": "experimental",
    "format_experiences": "experimental",
    "ContextPool": "experimental",
    "run_voice_pipeline": "experimental",
    "interrupt_turn": "experimental",
    # md2wechat (3O 内化, v4.20.0)
    "ResourceCatalog": "experimental",
    "AntiNoiseValidator": "experimental",
    "md_to_wechat_html": "experimental",
    "produce_article": "experimental",
    "publish_draft": "experimental",
    "ArticleStore": "experimental",
    # Graft (NanoNets, 3O 内化, v4.21.0)
    "semantic_build": "experimental",
    "incremental_refresh": "experimental",
    "stale_nodes": "experimental",
    "render_node_markdown": "experimental",
    "parse_wikilinks": "experimental",
    "write_agent_instructions": "experimental",
    "plan_wiring": "experimental",
    "list_agents": "experimental",
    # Graphify / Strix (3O 内化, v4.22.0)
    "KnowledgeGraph": "experimental",
    "semantic_to_graph": "experimental",
    "run_pentest_loop": "experimental",
    "verify_finding": "experimental",
    # TencentDB Agent Memory (3O 内化, v4.23.0)
    "rrf_merge": "experimental",
    "hybrid_search": "experimental",
    "bm25_score": "experimental",
    "DistillPipeline": "experimental",
    "AssetRegistry": "experimental",
    # Cypress (3O 内化, v4.24.0)
    "retry_until": "experimental",
    "wait_actionable": "experimental",
    "expect_eventually": "experimental",
    # FDE book (3O 内化, v4.25.0)
    "compute_health": "experimental",
    "watchdog": "experimental",
    "normalize": "experimental",
    # AiToEarn (3O 内化, v4.26.0)
    "publish_to": "experimental",
    "batch_draft": "experimental",
    "content_limits": "experimental",
    "register_platform": "experimental",
    "list_platforms": "experimental",
    "settle": "experimental",
    # Pixel2Motion (3O 内化, v4.27.0)
    "iou_score": "experimental",
    "svg_path_audit": "experimental",
    "smoothness_gate": "experimental",
    "complexity_ladder": "experimental",
    # FDE book 2/7章 (3O 内化, v4.28.0)
    "mvd_check": "experimental",
    "MvdPipeline": "experimental",
    "PlaybookLibrary": "experimental",
    "evaluate_productization": "experimental",
    # Auto-Deep-Research (3O 内化, v4.29.0)
    "tools_to_prompt": "experimental",
    "wrap_tools": "experimental",
    "parse_function_tags": "experimental",
    "convert_to_tool_calls": "experimental",
    "adapt_call": "experimental",
    # Dify (3O 内化, v4.30.0)
    "WorkflowDAG": "experimental",
    "topological_execute": "experimental",
    "validate_dsl": "experimental",
    "render_template": "experimental",
    "PluginRegistry": "experimental",
    # Dify Agent (3O 内化, v4.31.0)
    "run_agent": "experimental",
    "run_function_calling": "experimental",
    "run_react": "experimental",
    "run_plan": "experimental",
    # Deep-dive batch (2-8, v4.32.0)
    "FlowRunner": "experimental",
    "FlowBroker": "experimental",
    "BanditRouter": "experimental",
    "OffloadPipeline": "experimental",
    "SquadOrchestrator": "experimental",
    "parse_python_tree": "experimental",
    "Marketplace": "experimental",
    "fit_smooth_cubic": "experimental",
    # Remaining value batch (v4.33.0)
    "build_rag_pipeline": "experimental",
    "moderate": "experimental",
    "ConversationVars": "experimental",
    "CodeGraphBuilder": "experimental",
    "TriageFlow": "experimental",
    "HealthMonitor": "experimental",
}
